{% set name = "hashquery" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hashquery-{{ version }}.tar.gz
  sha256: 94837e6c75fc7ce27c5edab2d505ac21a246e04bcfa0412952c937314366b0a3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - typing-extensions
    - requests
    - pyarrow
    - pandas

test:
  imports:
    - hashquery
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hashboard-hq/hashquery
  summary: A Python framework for defining and querying BI models in your data warehouse 
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
